name: CI para VoteApp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Instalar Maven
      run: sudo apt-get install -y maven

    - name: Compilar proyecto (sin pruebas)
      run: mvn clean install -DskipTests

  test:
    runs-on: ubuntu-latest
    needs: build

    services:
      selenium:
        image: selenium/standalone-chrome:125.0
        ports:
          - 4444:4444
        options: >-
          --shm-size=2g

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Instalar Maven
      run: sudo apt-get install -y maven

    - name: Ejecutar pruebas unitarias y autónomas
      run: mvn test -Dtest=!RegisterFormGUITest

    - name: Ejecutar pruebas GUI con Selenium
      run: mvn test -Dtest=RegisterFormGUITest

    - name: Ejecutar pruebas de carga con JMeter
      run: mvn jmeter:jmeter

    - name: Copiar logs de JMeter
      run: mvn antrun:run@move-jmeter-logs

    - name: Ejecutar pruebas de API con Postman
      run: mvn exec:exec@postman-tests

    - name: Verificación final
      run: mvn verify
