name: CI para VoteApp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Instalar Maven
      run: sudo apt-get install -y maven

    - name: Compilar proyecto
      run: mvn clean install -DskipTests=true "-Dskip.jmeter=true" "-Dskip.postman=true"

    - name: Empaquetar jar
      run: mvn package -DskipTests

    - name: Guardar aplicación empaquetada
      uses: actions/upload-artifact@v3
      with:
        name: votacion-app
        path: target/demo-0.0.1-SNAPSHOT.jar

  test:
    runs-on: ubuntu-latest
    needs: build

    services:
      selenium:
        image: selenium/standalone-chrome:125.0
        ports:
          - 4444:4444
        options: >-
          --shm-size=2g

    steps:
    - name: Descargar artefacto
      uses: actions/download-artifact@v3
      with:
        name: votacion-app

    - name: Configurar Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Instalar Maven
      run: sudo apt-get install -y maven

    - name: Ejecutar la app (Spring Boot jar)
      run: |
        nohup java -jar demo-0.0.1-SNAPSHOT.jar &
        sleep 20

    - name: Pruebas Unitarias y Autónomas
      run: mvn test -Dtest=!RegisterFormGUITest

    - name: Pruebas de carga con JMeter
      run: mvn jmeter:jmeter

    - name: Copiar logs de JMeter
      run: mvn antrun:run@move-jmeter-logs

    - name: Pruebas GUI con Selenium
      run: mvn test -Dtest=RegisterFormGUITest

    - name: Pruebas API con Postman (Newman via Docker)
      run: |
        docker run --network host --rm \
          -v "${{ github.workspace }}/src/test/java/com/vote/demo/postman:/etc/newman" \
          postman/newman run /etc/newman/vote-demo.postman_collection.json
